services:
  backend:
    build: ./server
    command: ["./wait-for-db.sh", "db", "gunicorn", "wsgi:app", "--bind", "0.0.0.0:5000"]
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  frontend:
    build: ./kilo-client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: