"""initial tables

Revision ID: dd4e367cd6c2
Revises: 
Create Date: 2026-03-12 16:43:05.597342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4e367cd6c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=160), nullable=False),
    sa.Column('last_name', sa.String(length=160), nullable=False),
    sa.Column('kilo_access', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_id'), ['id'], unique=False)

    op.create_table('officer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=160), nullable=False),
    sa.Column('last_name', sa.String(length=160), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=True),
    sa.Column('kilo_access', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officer_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_officer_id'), ['id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('officer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officer_id'))
        batch_op.drop_index(batch_op.f('ix_officer_first_name'))

    op.drop_table('officer')
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_athlete_first_name'))

    op.drop_table('athlete')
    # ### end Alembic commands ###
